### ISSUE TITLE
Mock is purged but not invocation on it.

### ISSUE THREAD

**Issue by maciejmikosik** [maciejmikosik/testory#101]
```
import static org.testory.Testory.*;

import org.junit.Test;

public class TestPurging {
  @Test
  public void test() {
    // test 1
    Object mock = mock(Object.class);
    when("");
    mock.toString();

    // test 2
    when("");

    // test 3
    when("");
    thenCalled(onInstance(mock(Object.class)));
  }
}
```
causes 

```
org.testory.TestoryException: expected mock
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.testory.plumbing.Checker.fail(Checker.java:73)
	at org.testory.plumbing.Checker.mock(Checker.java:56)
	at org.testory.plumbing.CheckingProxer$1.handle(CheckingProxer.java:28)
	at org.testory.proxy.proxer.WrappingProxer$1.handle(WrappingProxer.java:44)
	at org.testory.proxy.proxer.TypeSafeProxer$1.handle(TypeSafeProxer.java:37)
	at org.testory.proxy.proxer.WrappingProxer$1.handle(WrappingProxer.java:44)
	at org.testory.proxy.proxer.CglibProxer$3.intercept(CglibProxer.java:121)
	at org.testory.proxy.proxer.CglibProxer$ProxiableObject$$$EnhancerByCGLIB$$c288f4b3.toString(<generated>)
	at java.lang.String.valueOf(String.java:2994)
	at org.testory.common.Formatter.format(Formatter.java:21)
	at org.testory.plumbing.QuietFormatter.format(QuietFormatter.java:32)
	at org.testory.plumbing.QuietFormatter.format(QuietFormatter.java:41)
	at org.testory.plumbing.QuietFormatter.format(QuietFormatter.java:30)
	at org.testory.facade.DefaultFacade.formatInvocations(DefaultFacade.java:711)
	at org.testory.facade.DefaultFacade.thenCalledTimes(DefaultFacade.java:647)
	at org.testory.facade.DefaultFacade.thenCalled(DefaultFacade.java:596)
	at org.testory.Testory.thenCalled(Testory.java:287)
	at TestPurging.test(TestPurging.java:21)
```

Calling `when` in test 3, causes mock created in test 1 to be purged. However `toString` invocation on that mock is not purged because it is below `when`.

Assertion in test 3 fails and tries to print all historical invocations. It tries to print `toString` invocation from test 1. It validates if instance is mock and it isn't because mock was purged. 

using testory 1.2.1

**Comment by maciejmikosik** [comment]
Changed purging logic to purge misplaced invocations.
